### ISSUE TITLE
Nicknames in Civi cause collision for decidim authentication

### ISSUE THREAD

**Issue by BigSnicker** [Green-Party-of-Canada-Members/gpc-decidim#76] opened 2022-10-11 23:59 UTC
As discussed, some Civi subscribers have nicknames used to indicate common usage (e.g. "Steven" might have a nickname of "Steve").

This produces an error message saying "Could not authenticate you from Civicrm because "Another account is using the same email address".

Ideally, the solution will allow for existing nicknames to be maintained, possibly by using them + Lastname to help improve uniqueness.

**Comment by Laurence-Montgomery** [comment] 2022-10-13 16:58
How do we know that it is the nick names causing the problem? Is there a workaround? (Perhaps simply removing the nickname from Civi?)

**Comment by microstudi** [comment] 2022-10-20 11:19
This should be solved now

**Comment by BigSnicker** [comment] 2023-08-03 02:04
This problem appears to have come back.

We're again getting nicknames produce "Could not authenticate you from Civicrm because Another account is using the same email address".

**Comment by microstudi** [comment] 2023-08-18 09:58
This issue is really caused by another one (but the message returned by Decidim is misleading). Here is the report https://github.com/decidim/decidim/issues/11489

Ha have it fixed in the module civicrm, so it should be ok now.

**Closed** 2024-05-26 17:15 UTC
Labels: priority-high
